# <u>**Assignment-03 - Tidying Data**</u>
# **Submitted By - Muhammad Anas Nasir**
# **Registration No. FA23-BBD-086**
# **Class - BDA-4C**
-------

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('ANAS NASIR.csv')

In [17]:
head = df.head(15)
head

,Unnamed: 0,Name,CURRENCY,1996,1997,1998,1999,2000,2001,2002,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,0.0,BANK AL HABIB LTD - Loans_Net,PR,0,7418119.00,8012713.00,12515349.00,16212099.0,18216556.0,24580594.0,...,74552548.0,79502744.0,95160025.0,109874395.0,1.266043e+08,1.195590e+08,1.541555e+08,1.657063e+08,1.657010e+08,1.935926e+08
1,0.0,BANK AL HABIB LTD - Prov_Loss,PR,0,37167.00,-18464.00,4423.00,0.0,52144.0,118632.0,...,19652.0,92687.0,984987.0,1183026.0,9.462960e+05,1.820788e+06,4.661010e+05,4.797910e+05,5.584520e+05,1.965335e+06
2,0.0,BANK AL HABIB LTD - Total_Assets,PR,0,16514506.00,16897148.00,19870187.00,24137694.0,28976835.0,49437129.0,...,115260316.0,141338235.0,177329929.0,249817072.0,3.017963e+08,3.845256e+08,4.533539e+08,4.610219e+08,5.793104e+08,6.400238e+08
3,0.0,BANK AL HABIB LTD - Non_performing_loans,PR,0,181833.00,54949.00,131028.00,0.0,0.0,0.0,...,0.0,0.0,0.0,2067656.0,2.943863e+06,3.203630e+06,3.705730e+06,3.699903e+06,5.024778e+06,5.874374e+06
4,0.0,BANK AL HABIB LTD - %Tot loans,PR,0,2.43,0.68,1.05,0.0,0.0,0.0,...,0.0,0.0,0.0,1.7,2.270000e+00,2.570000e+00,2.320000e+00,2.150000e+00,2.920000e+00,2.910000e+00
5,0.0,BANK AL HABIB LTD - Shareholderrs_equity,PR,0,851119.00,1016291.00,1169019.00,1322197.0,1532135.0,1821861.0,...,6184385.0,7997287.0,9912062.0,12282855.0,1.474411e+07,1.787866e+07,2.128364e+07,2.547149e+07,3.291259e+07,3.807856e+07
6,0.0,WC03058,0,"$$ER: 4540,NO DATA VALUES FOUND",0.00,0.00,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
7,0.0,BANK AL HABIB LTD - Customer_Liability,PR,0,15708650.00,2912679.00,4684619.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
8,0.0,BANK AL HABIB LTD - Total_Deposits,PR,0,13445196.00,13225945.00,14112870.00,17585388.0,24696787.0,34240158.0,...,91371949.0,114818032.0,144340496.0,189148427.0,2.497609e+08,3.020972e+08,3.403866e+08,3.720290e+08,4.366527e+08,5.036934e+08
9,0.0,BANK AL HABIB LTD - Total_debt,PR,0,1802577.00,2217715.00,4182305.00,4686318.0,1021249.0,2184172.0,...,12551351.0,15715644.0,17776719.0,41551000.0,3.041198e+07,5.581170e+07,8.136855e+07,5.620885e+07,9.984276e+07,8.675646e+07
10,0.0,BANK AL HABIB LTD - Total_liabilities,PR,0,15663387.00,15880857.00,18701168.00,22815497.0,27288039.0,46845442.0,...,108640766.0,132924815.0,165651265.0,235596543.0,2.855796e+08,3.645143e+08,4.291755e+08,4.354407e+08,5.462839e+08,6.018323e+08
11,0.0,BANK AL HABIB LTD - Total_liabilities & Shareh...,PR,0,16514506.00,16897148.00,19870187.00,24137694.0,28976835.0,49437129.0,...,115260316.0,141338235.0,177329929.0,249817072.0,3.017963e+08,3.845256e+08,4.533539e+08,4.610219e+08,5.793104e+08,6.400238e+08
12,0.0,WC03101,0,"$$ER: 4540,NO DATA VALUES FOUND",0.00,0.00,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
13,0.0,WC01051,0,"$$ER: 4540,NO DATA VALUES FOUND",0.00,0.00,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
14,0.0,WC18197,0,"$$ER: 4540,NO DATA VALUES FOUND",0.00,0.00,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

**Panel financial data** (Bank Al-Habib Limited) with metrics spanning **1996-2015**. The layout is wide with columns like **Name**, **Currency** followed by year columns **(1995-2015)**. There are many missing values non-numeric entries (metric labels, error codes) in value columns.

In [9]:
stacked_data = df.stack()
stacked = stacked_data.head(15)
stacked

0  Unnamed: 0                              0.0
   Name          BANK AL HABIB LTD - Loans_Net
   CURRENCY                                 PR
   1996                                      0
   1997                              7418119.0
   1998                              8012713.0
   1999                             12515349.0
   2000                             16212099.0
   2001                             18216556.0
   2002                             24580594.0
   2003                             35805164.0
   2004                             52219222.0
   2005                             55746009.0
   2006                             74552548.0
   2007                             79502744.0
dtype: object

The above code converts the dataset from wide to long by collapsing years columns into rows, creating a multi-index Series. Result shows metrics names paired with year values (e.g, "BANK AL HABIB LTD - Loans_Net" for 1996, 1997, etc). Mixed datatypes present string and numeric values requiring further tidying and type conversation.

In [ ]:
reset_indexed = df.reset_index()
reset_indexed.head(15)

,index,Unnamed: 0,Name,CURRENCY,1996,1997,1998,1999,2000,2001,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,0,0.0,BANK AL HABIB LTD - Loans_Net,PR,0,7418119.00,8012713.00,12515349.00,16212099.0,18216556.0,...,74552548.0,79502744.0,95160025.0,109874395.0,1.266043e+08,1.195590e+08,1.541555e+08,1.657063e+08,1.657010e+08,1.935926e+08
1,1,0.0,BANK AL HABIB LTD - Prov_Loss,PR,0,37167.00,-18464.00,4423.00,0.0,52144.0,...,19652.0,92687.0,984987.0,1183026.0,9.462960e+05,1.820788e+06,4.661010e+05,4.797910e+05,5.584520e+05,1.965335e+06
2,2,0.0,BANK AL HABIB LTD - Total_Assets,PR,0,16514506.00,16897148.00,19870187.00,24137694.0,28976835.0,...,115260316.0,141338235.0,177329929.0,249817072.0,3.017963e+08,3.845256e+08,4.533539e+08,4.610219e+08,5.793104e+08,6.400238e+08
3,3,0.0,BANK AL HABIB LTD - Non_performing_loans,PR,0,181833.00,54949.00,131028.00,0.0,0.0,...,0.0,0.0,0.0,2067656.0,2.943863e+06,3.203630e+06,3.705730e+06,3.699903e+06,5.024778e+06,5.874374e+06
4,4,0.0,BANK AL HABIB LTD - %Tot loans,PR,0,2.43,0.68,1.05,0.0,0.0,...,0.0,0.0,0.0,1.7,2.270000e+00,2.570000e+00,2.320000e+00,2.150000e+00,2.920000e+00,2.910000e+00
5,5,0.0,BANK AL HABIB LTD - Shareholderrs_equity,PR,0,851119.00,1016291.00,1169019.00,1322197.0,1532135.0,...,6184385.0,7997287.0,9912062.0,12282855.0,1.474411e+07,1.787866e+07,2.128364e+07,2.547149e+07,3.291259e+07,3.807856e+07
6,6,0.0,WC03058,0,"$$ER: 4540,NO DATA VALUES FOUND",0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
7,7,0.0,BANK AL HABIB LTD - Customer_Liability,PR,0,15708650.00,2912679.00,4684619.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
8,8,0.0,BANK AL HABIB LTD - Total_Deposits,PR,0,13445196.00,13225945.00,14112870.00,17585388.0,24696787.0,...,91371949.0,114818032.0,144340496.0,189148427.0,2.497609e+08,3.020972e+08,3.403866e+08,3.720290e+08,4.366527e+08,5.036934e+08
9,9,0.0,BANK AL HABIB LTD - Total_debt,PR,0,1802577.00,2217715.00,4182305.00,4686318.0,1021249.0,...,12551351.0,15715644.0,17776719.0,41551000.0,3.041198e+07,5.581170e+07,8.136855e+07,5.620885e+07,9.984276e+07,8.675646e+07
10,10,0.0,BANK AL HABIB LTD - Total_liabilities,PR,0,15663387.00,15880857.00,18701168.00,22815497.0,27288039.0,...,108640766.0,132924815.0,165651265.0,235596543.0,2.855796e+08,3.645143e+08,4.291755e+08,4.354407e+08,5.462839e+08,6.018323e+08
11,11,0.0,BANK AL HABIB LTD - Total_liabilities & Shareh...,PR,0,16514506.00,16897148.00,19870187.00,24137694.0,28976835.0,...,115260316.0,141338235.0,177329929.0,249817072.0,3.017963e+08,3.845256e+08,4.533539e+08,4.610219e+08,5.793104e+08,6.400238e+08
12,12,0.0,WC03101,0,"$$ER: 4540,NO DATA VALUES FOUND",0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
13,13,0.0,WC01051,0,"$$ER: 4540,NO DATA VALUES FOUND",0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
14,14,0.0,WC18197,0,"$$ER: 4540,NO DATA VALUES FOUND",0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

Each row represents a different financial metric of Bank AL- Habib Ltd, including items such as **Loans Net**, **Total Assets**, **Deposits**, and **Shareholder's Equity**, with corresponding numeric numerical values listed for each year from 1996 to 2007. 
The data is structured so that each finacial variable appears as a seperate row containing a full time series of annual data. One of the rows contains corrupted text instead of numeric values, indicating that the dataset includes at least one improperly imported or malformed entry that will require cleaning.

In [ ]:
reset_indexed.rename(columns={'Unnamed: 0': 'Bank_ID'}, inplace=True)
print("Column renamed: 'Unnamed: 0' → 'Bank_ID'")

print("\nDataframe columns:")
print(reset_indexed.columns.tolist())

print("\nFirst 10 rows with renamed column:")
reset_indexed.head(10)

Column renamed: 'Unnamed: 0' → 'Bank_ID'

Dataframe columns:
['index', 'Bank_ID', 'Name', 'CURRENCY', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']

First 10 rows with renamed column:

,index,Bank_ID,Name,CURRENCY,1996,1997,1998,1999,2000,2001,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,0,0.0,BANK AL HABIB LTD - Loans_Net,PR,0,7418119.00,8012713.00,12515349.00,16212099.0,18216556.0,...,74552548.0,79502744.0,95160025.0,109874395.0,1.266043e+08,1.195590e+08,1.541555e+08,1.657063e+08,1.657010e+08,1.935926e+08
1,1,0.0,BANK AL HABIB LTD - Prov_Loss,PR,0,37167.00,-18464.00,4423.00,0.0,52144.0,...,19652.0,92687.0,984987.0,1183026.0,9.462960e+05,1.820788e+06,4.661010e+05,4.797910e+05,5.584520e+05,1.965335e+06
2,2,0.0,BANK AL HABIB LTD - Total_Assets,PR,0,16514506.00,16897148.00,19870187.00,24137694.0,28976835.0,...,115260316.0,141338235.0,177329929.0,249817072.0,3.017963e+08,3.845256e+08,4.533539e+08,4.610219e+08,5.793104e+08,6.400238e+08
3,3,0.0,BANK AL HABIB LTD - Non_performing_loans,PR,0,181833.00,54949.00,131028.00,0.0,0.0,...,0.0,0.0,0.0,2067656.0,2.943863e+06,3.203630e+06,3.705730e+06,3.699903e+06,5.024778e+06,5.874374e+06
4,4,0.0,BANK AL HABIB LTD - %Tot loans,PR,0,2.43,0.68,1.05,0.0,0.0,...,0.0,0.0,0.0,1.7,2.270000e+00,2.570000e+00,2.320000e+00,2.150000e+00,2.920000e+00,2.910000e+00
5,5,0.0,BANK AL HABIB LTD - Shareholderrs_equity,PR,0,851119.00,1016291.00,1169019.00,1322197.0,1532135.0,...,6184385.0,7997287.0,9912062.0,12282855.0,1.474411e+07,1.787866e+07,2.128364e+07,2.547149e+07,3.291259e+07,3.807856e+07
6,6,0.0,WC03058,0,"$$ER: 4540,NO DATA VALUES FOUND",0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
7,7,0.0,BANK AL HABIB LTD - Customer_Liability,PR,0,15708650.00,2912679.00,4684619.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
8,8,0.0,BANK AL HABIB LTD - Total_Deposits,PR,0,13445196.00,13225945.00,14112870.00,17585388.0,24696787.0,...,91371949.0,114818032.0,144340496.0,189148427.0,2.497609e+08,3.020972e+08,3.403866e+08,3.720290e+08,4.366527e+08,5.036934e+08
9,9,0.0,BANK AL HABIB LTD - Total_debt,PR,0,1802577.00,2217715.00,4182305.00,4686318.0,1021249.0,...,12551351.0,15715644.0,17776719.0,41551000.0,3.041198e+07,5.581170e+07,8.136855e+07,5.620885e+07,9.984276e+07,8.675646e+07

The dataframe shows financial data for banks in a wide panel format. Each row represent a specific financial metric for one bank (identified by Bank_ID). The columns labeled 1996-2010 show the year-wise values of that metric. Teh metrics include items such as **Loans_Net**, **Prov_Loss**, **Total_Assets**, **Non-performing_loans**, **%Tot loans** and **Shareholders_equity**.

In [18]:
bank_split = reset_indexed['Name'].str.split(pat=' - ', expand=True)

bank_split.insert(0, 'Bank_ID', reset_indexed['Bank_ID'].values)

bank_split.columns = ['Bank_ID', 'Bank_Name', 'Metric', 'Additional']

print("Split 'Name' column with Bank_ID:")
print(f"Shape: {bank_split.shape}")
print("\nFirst 15 rows:")
print(bank_split.head(15))

Split 'Name' column with Bank_ID:
Shape: (840, 4)

First 15 rows:
    Bank_ID          Bank_Name                           Metric Additional
0       0.0  BANK AL HABIB LTD                        Loans_Net       None
1       0.0  BANK AL HABIB LTD                        Prov_Loss       None
2       0.0  BANK AL HABIB LTD                     Total_Assets       None
3       0.0  BANK AL HABIB LTD             Non_performing_loans       None
4       0.0  BANK AL HABIB LTD                       %Tot loans       None
5       0.0  BANK AL HABIB LTD             Shareholderrs_equity       None
6       0.0            WC03058                             None       None
7       0.0  BANK AL HABIB LTD               Customer_Liability       None
8       0.0  BANK AL HABIB LTD                   Total_Deposits       None
9       0.0  BANK AL HABIB LTD                       Total_debt       None
10      0.0  BANK AL HABIB LTD                Total_liabilities       None
11      0.0  BANK AL HABIB LTD  Total_liabilities & Shareholder       None
12      0.0            WC03101                             None       None
13      0.0            WC01051                             None       None
14      0.0            WC18197                             None       None

In [16]:
id_vars = ['Bank_ID', 'Name', 'CURRENCY']

year_columns = [col for col in reset_indexed.columns if col not in id_vars and col != 'index']

# Melt the dataset
melted_full = reset_indexed.melt(
    id_vars=id_vars,
    value_vars=year_columns,
    var_name='Year',
    value_name='Value'
)

print("="*70)
print("Melted dataset - Wide to Long Format")
print("="*70)
print(f"Original shape: {reset_indexed.shape}")
print(f"Melted shape: {melted_full.shape}")
print(f"\nColumns: {melted_full.columns.tolist()}")
print(f"\nFirst 20 rows of melted data:")
print(melted_full.head(20))

======================================================================
Melted dataset - Wide to Long Format
======================================================================
Original shape: (840, 24)
Melted shape: (16800, 5)

Columns: ['Bank_ID', 'Name', 'CURRENCY', 'Year', 'Value']

First 20 rows of melted data:
    Bank_ID                                               Name CURRENCY  Year  \
0       0.0                      BANK AL HABIB LTD - Loans_Net       PR  1996
1       0.0                      BANK AL HABIB LTD - Prov_Loss       PR  1996
2       0.0                   BANK AL HABIB LTD - Total_Assets       PR  1996
3       0.0           BANK AL HABIB LTD - Non_performing_loans       PR  1996
4       0.0                     BANK AL HABIB LTD - %Tot loans       PR  1996
5       0.0           BANK AL HABIB LTD - Shareholderrs_equity       PR  1996
6       0.0                                            WC03058        0  1996
7       0.0             BANK AL HABIB LTD - Customer_Liability       PR  1996
8       0.0                 BANK AL HABIB LTD - Total_Deposits       PR  1996
9       0.0                     BANK AL HABIB LTD - Total_debt       PR  1996
10      0.0              BANK AL HABIB LTD - Total_liabilities       PR  1996
11      0.0  BANK AL HABIB LTD - Total_liabilities & Shareh...       PR  1996
12      0.0                                            WC03101        0  1996
13      0.0                                            WC01051        0  1996
14      0.0                                            WC18197        0  1996
15      0.0              BANK AL HABIB LTD - Common_net_income       PR  1996
16      0.0               BANK AL HABIB LTD - Basic_net_income       PR  1996
17      0.0              BANK AL HABIB LTD - Minority_interest       PR  1996
18      0.0                BANK AL HABIB LTD - Interest_income       PR  1996
19      0.0               BANK AL HABIB LTD - Interest_expense       PR  1996

                              Value
0                                 0
1                                 0
2                                 0
3                                 0
4                                 0
5                                 0
6   $$ER: 4540,NO DATA VALUES FOUND
7                                 0
8                                 0
9                                 0
10                                0
11                                0
12  $$ER: 4540,NO DATA VALUES FOUND
13  $$ER: 4540,NO DATA VALUES FOUND
14  $$ER: 4540,NO DATA VALUES FOUND
15                                0
16                                0
17                                0
18                                0
19                                0

The output indicates that the column was split using an incorrect pattern, so Pandas seperated the text mainly by spaces. Rows containing full bank names and metrics were split reasonably well, but rows were misalligned, leaving empty metric fields. 
Overall, the split worked inconsistenly because the pattern didn't match the actual data structure.

----

## **End of Assignment** :)